package com.qazi.calendar.calendar_backend;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "events") // Maps to MongoDB collection
public class EventTest {
    @Id
    private String id; // Automatically generated by MongoDB
    private String name;
    private String type;
    private String startTime;
    private String endTime;
    private String color;

    // No-args constructor
    public EventTest() {}

    // All-args constructor
    public EventTest(String name, String type, String startTime, String endTime) {
        this.name = name;
        this.type = type;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public EventTest(String name, String type, String startTime, String endTime, String color) {
        this.name = name;
        this.type = type;
        this.startTime = startTime;
        this.endTime = endTime;
        this.color = color;
    }

    //getters and setters

    public String getId() {
        return id;
    }
    public void setId(String Id) {
        this.id = Id;
    }
    public void setName(String name) {
        this.name = name;
    }
    public void setType(String type) {
        this.type = type;
    }
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    public void setColour(String color) {
        this.color = color;
    }
    public String getName() {
        return name;
    }
    public String getType() {
        return type;
    }
    public String getStartTime() {
        return startTime;
    }
    public String getEndTime() {
        return endTime;
    }

}

